<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ELEMENT note (messages)>
<!ATTLIST note date CDATA #REQUIRED>
<!ATTLIST messages id CDATA #REQUIRED>
<!ELEMENT messages (to, from, heading, body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>
<note date="2024/7/14">
<messages id="1">
<to>Sheela</to>
<from>Shobi</from>
<heading>Reminder</heading>
<body>Don't forget to read for exam!</body>
</messages>
<messages id="2">
<to>Ram</to>
<from>Shyam</from>
<heading>Alert</heading>
<body>Watch Out! There is a thief in your house.</body>
</messages>

</note>